aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_DC31_L3_LEAF_2_1_Ethernet3
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC31_L3_LEAF_2_1
  peer_interface: Ethernet3
  peer_type: l3leaf
- name: Ethernet2
  description: L2_DC31_L3_LEAF_2_2_Ethernet3
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: DC31_L3_LEAF_2_2
  peer_interface: Ethernet3
  peer_type: l3leaf
- name: Ethernet4
  description: SERVER_DC31_SERVER_2_iLO
  shutdown: false
  spanning_tree_portfast: edge
  peer: DC31_SERVER_2
  peer_interface: iLO
  peer_type: server
  switchport:
    enabled: true
    mode: access
    access_vlan: 11
hostname: DC31_L2_LEAF_2_1
ip_domain_lookup:
  source_interfaces:
  - name: Management1
    vrf: MGMT
ip_igmp_snooping:
  globally_enabled: true
ip_name_servers:
- ip_address: 172.19.177.131
  vrf: MGMT
is_deployed: true
local_users:
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1.
- name: cvpadmin
  privilege: 15
  role: network-admin
  no_password: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.19.180.23/20
  type: oob
  gateway: 172.19.177.131
metadata:
  platform: cEOS-lab
  fabric_name: FABRIC
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.pool.ntp.org
    preferred: true
    vrf: MGMT
port_channel_interfaces:
- name: Port-Channel1
  description: L2_DC31_L3_LEAVES_2_Port-Channel3
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 11-12,21-22,3401-3402
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 172.19.177.131
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 11
  name: VRF10_VLAN11
  tenant: TENANT1
- id: 12
  name: VRF10_VLAN12
  tenant: TENANT1
- id: 21
  name: VRF11_VLAN21
  tenant: TENANT1
- id: 22
  name: VRF11_VLAN22
  tenant: TENANT1
- id: 3401
  name: L2_VLAN3401
  tenant: TENANT1
- id: 3402
  name: L2_VLAN3402
  tenant: TENANT1
vrfs:
- name: MGMT
  ip_routing: false
