aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_DC31_SPINE_1_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.1/31
  peer: DC31_SPINE_1
  peer_interface: Ethernet1
  peer_type: spine
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_DC31_SPINE_2_Ethernet1
  shutdown: false
  mtu: 1500
  ip_address: 10.255.255.3/31
  peer: DC31_SPINE_2
  peer_interface: Ethernet1
  peer_type: spine
  switchport:
    enabled: false
hostname: DC31_LEAF_1_1
ip_domain_lookup:
  source_interfaces:
  - name: Management1
    vrf: MGMT
ip_name_servers:
- ip_address: 172.19.177.131
  vrf: MGMT
ip_routing: true
is_deployed: true
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  no_password: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.255.0.3/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.19.180.11/20
  type: oob
  gateway: 172.19.177.131
metadata:
  platform: cEOS-lab
  rack: '1'
  fabric_name: FABRIC
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.pool.ntp.org
    preferred: true
    vrf: MGMT
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.0.0/27 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bgp:
  as: '65101'
  router_id: 10.255.0.3
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    type: ipv4
    password: 7x4B4rnJhZB438m9+BrBfQ==
    send_community: all
    maximum_routes: 12000
  neighbors:
  - ip_address: 10.255.255.0
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    peer: DC31_SPINE_1
    description: DC31_SPINE_1_Ethernet1
  - ip_address: 10.255.255.2
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65100'
    peer: DC31_SPINE_2
    description: DC31_SPINE_2_Ethernet1
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 172.19.177.131
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
