---
type: spine

spine:
  # Define variables for all nodes of this type
  defaults:
    # Used platform
    platform: cEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Autonous System Number for BGP
    node_groups:
      - group: DC31_SPINES
        bgp_as: 65100
        # Define variables per node
        nodes:
          # The Node Name is used as "hostname"
          - name: DC31_SPINE_1
            # Unique identifier used for IP addressing and other algorithms
            id: 1
            # Node management interface IPv4 address
            mgmt_ip: 172.19.180.1/20

          - name: DC31_SPINE_2
            id: 2
            mgmt_ip: 172.19.180.2/20
