all:
  children:
    FABRIC:
      children:
        DC31:
          children:
            DC31_SPINES:
              hosts:
                DC31_SPINE_1:
                DC31_SPINE_2:

            DC31_L3_LEAVES:
              hosts:
                DC31_L3_LEAF_1_1:
                DC31_L3_LEAF_1_2:
                DC31_L3_LEAF_2_1:
                DC31_L3_LEAF_2_2:
                  
            # DC31_L2_LEAVES:
            #   hosts:
            #     DC31_L2_LEAF_1_1:
            #     DC31_L2_LEAF_2_1:

    NETWORK_SERVICES:
      children:
        DC31_L3_LEAVES:
        DC31_L2_LEAVES:
    CONNECTED_ENDPOINTS:
      children:
        DC31_L3_LEAVES:
        DC31_L2_LEAVES: