---
fabric_name: FABRIC

# Generate CSVs with fabric link info.
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Local users
local_users:
  - name: cvpadmin
    privilege: 15
    role: network-admin
    no_password: true

# Under/overlay routing protocol
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# DNS
dns_settings:
  servers:
    - ip_address: 172.19.177.131

# NTP
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 0.pool.ntp.org

# P2P
p2p_uplinks_mtu: 1500

default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-4]
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    mlag_interfaces: [Ethernet7-8]

node_type_keys:
  - key: spine
    type: spine
  - key: l3leaf
    type: l3leaf

spine:
    # Define variables for all nodes of this type
  defaults:
    # Used platform
    platform: cEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
  node_groups:
    - group: DC31_SPINES
      bgp_as: 65100
      nodes:
        # The Node Name is used as "hostname"
        - name: DC31_SPINE_1
          # Unique identifier used for IP addressing and other algorithms
          id: 1
          # Node management interface IPv4 address
          rack: '1'
          mgmt_ip: 172.19.180.1/20

        - name: DC31_SPINE_2
          id: 2
          rack: '2'
          mgmt_ip: 172.19.180.2/20

l3leaf:
  defaults:
      platform: cEOS-lab

      # Address pool for loopback0 used for BGP EVPN sessions
      loopback_ipv4_pool: 10.255.0.0/27

      # Offset - num of spine swt
      loopback_ipv4_offset: 2

      # Address pool for Virtual Tunnel EndPoint (VxLAN src/dst)
      vtep_loopback_ipv4_pool: 10.255.1.0/27

      # Ansible device hostnames for establishing neighborship
      uplink_switches: ['DC31_SPINE_1', 'DC31_SPINE_2']

      # Address pool for uplink
      uplink_ipv4_pool: 10.255.255.0/27

      # Address pool for MLAG
      mlag_peer_ipv4_pool: 10.255.1.64/27

      # Address pool for iBGP peering between MLAG
      mlag_peer_l3_ipv4_pool: 10.255.1.96/27

      # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
      virtual_router_mac_address: 00:1c:73:00:00:99
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp

  node_groups:
    - group: DC31_LEAVES_1
      bgp_as: 65101
      nodes:
      - name: DC31_LEAF_1_1
        id: 1
        rack: '1'
        mgmt_ip: 172.19.180.11/20
        uplink_switch_interfaces: [Ethernet1, Ethernet1] 

      - name: DC31_LEAF_1_2
        id: 2
        rack: '1'
        mgmt_ip: 172.19.180.12/20
        uplink_switch_interfaces: [Ethernet2, Ethernet2]

    - group: DC31_LEAVES_2
      bgp_as: 65102
      nodes:
      - name: DC31_LEAF_2_1
        id: 3
        rack: '2'
        mgmt_ip: 172.19.180.21/20
        uplink_switch_interfaces: [Ethernet3, Ethernet3]

      - name: DC31_LEAF_2_2
        id: 4
        rack: '2'
        mgmt_ip: 172.19.180.22/20
        uplink_switch_interfaces: [Ethernet4, Ethernet4]
