---
fabric_name: FABRIC

# Generate CSVs with fabric link info.
eos_designs_documentation:
  topology_csv: true
  p2p_links_csv: true

# Local users
local_users:
  - name: cvpadmin
    privilege: 15
    role: network-admin
    no_password: true

# Under/overlay routing protocol
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# DNS
dns_settings:
  servers:
    - ip_address: 172.19.177.131

# NTP
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 0.pool.ntp.org

# P2P
p2p_uplinks_mtu: 1500

bgp_peer_groups: 
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# Default interfaces for each node type
default_interfaces:
  - types: [spine]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    downlink_interfaces: [Ethernet1-8]
  - types: [l3leaf]
    platforms: [default]
    uplink_interfaces: [Ethernet1-2]
    mlag_interfaces: [Ethernet7-8]

servers:
- name: DC31_SERVER_1
  adapters:
      # Server's interfaces
    - endpoint_ports: [Ethernet1, Ethernet2]
      # Switches and its interfaces
      switches: [DC31_LEAF_1_1, DC31_LEAF_1_2]
      switch_ports: [Ethernet3, Ethernet3]

      # VLANs
      vlans: 11-12,21-22
      native_vlan: 4092

      # L2 mode of the port.
      mode: trunk
      # Spanning tree portfast configuration on this port.
      spanning_tree_portfast: edge

      port_channel:
        mode: active

- name: DC31_SERVER_2
  adapters:
    - endpoint_ports: [Ethernet1, Ethernet2]
      switch_ports: [Ethernet4, Ethernet4]
      switches: [DC31_LEAF_2_1, DC31_LEAF_2_2]
      vlans: 11-12,21-22
      native_vlan: 4092
      mode: access
      spanning_tree_portfast: edge

      port_channel:
        mode: active
