---
node_type_keys:
  - key: l3leaf
    type: l3leaf

# Variables for l3leaf
l3leaf:
  defaults:
      platform: cEOS-lab
      loopback_ipv4_pool: 10.255.0.0/27
      # Offset - num of spine swt
      loopback_ipv4_offset: 2

      # Address pool for Virtual Tunnel EndPoint (VxLAN src/dst)
      vtep_loopback_ipv4_pool: 10.255.1.0/27

      uplink_switches: ['DC31_SPINE_1', 'DC31_SPINE_2']
      uplink_ipv4_pool: 10.255.255.0/27
      uplink_interfaces: ['Ethernet1', 'Ethernet2']      


      # mlag_peer_ipv4_pool: 11.255.0.0/30
      # # Address pool for iBGP peering between MLAG
      # mlag_peer_l3_ipv4_pool: 11.255.1.0/30
      # mlag_interfaces: ['Ethernet5', 'Ethernet6']

      # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
      virtual_router_mac_address: 00:1c:73:00:00:99
      spanning_tree_priority: 4096
      spanning_tree_mode: mstp

  node_groups:
    - group: DC31_LEAVES_1
      bgp_as: 65101
      mlag_peer_l3_ipv4_pool: 11.255.1.0/30
      mlag_peer_ipv4_pool: 11.255.0.0/30
      nodes:
      - name: DC31_LEAF_1_1
        id: 1
        rack: '1'
        mgmt_ip: 172.19.180.11/20
        uplink_switch_interfaces: [Ethernet1, Ethernet1]
        mlag_interfaces: ['Ethernet5', 'Ethernet6']

      - name: DC31_LEAF_1_2
        id: 2
        rack: '1'
        mgmt_ip: 172.19.180.12/20
        uplink_switch_interfaces: [Ethernet2, Ethernet2]
        mlag_interfaces: ['Ethernet5', 'Ethernet6']

    - group: DC31_LEAVES_2
      bgp_as: 65102
      mlag_peer_l3_ipv4_pool: 11.255.1.4/30
      mlag_peer_ipv4_pool: 11.255.0.4/30
      nodes:
      - name: DC31_LEAF_2_1
        id: 3
        rack: '2'
        mgmt_ip: 172.19.180.21/20
        uplink_switch_interfaces: [Ethernet3, Ethernet3]
        mlag_interfaces: ['Ethernet5', 'Ethernet6']

      - name: DC31_LEAF_2_2
        id: 4
        rack: '2'
        mgmt_ip: 172.19.180.22/20
        uplink_switch_interfaces: [Ethernet4, Ethernet4]
        mlag_interfaces: ['Ethernet5', 'Ethernet6']
